-- Estrutura online do Projeto ENSO.
-- Execute este arquivo uma única vez no SQL Editor do Supabase.

create table if not exists public.operacoes (
  id bigint generated by default as identity primary key,
  os text not null unique,
  cliente text not null default 'NÃO INFORMADO',
  indicador text not null,
  documento text,
  modal text,
  horario double precision,
  status_meta text,
  tipo_operacao text,
  operacao text,
  regime text,
  data_operacao timestamp without time zone,
  tempo_os_min double precision,
  tempo_permanencia_min double precision,
  meta_min double precision
);

create index if not exists operacoes_indicador_idx on public.operacoes (indicador);
create index if not exists operacoes_modal_idx on public.operacoes (modal);
create index if not exists operacoes_cliente_idx on public.operacoes (cliente);
create index if not exists operacoes_status_idx on public.operacoes (status_meta);
create index if not exists operacoes_data_idx on public.operacoes (data_operacao);

create table if not exists public.importacoes (
  id bigint generated by default as identity primary key,
  arquivo text not null,
  importado_em timestamp with time zone not null default now(),
  registros integer not null default 0,
  analisados integer not null default 0,
  duplicados_descartados integer not null default 0
);

alter table public.operacoes enable row level security;
alter table public.importacoes enable row level security;

-- A chave pública pode somente consultar. Inclusão e substituição da base
-- serão feitas pelo sincronizador local usando uma chave secreta.
drop policy if exists "Consulta pública de operações" on public.operacoes;
create policy "Consulta pública de operações"
  on public.operacoes for select to anon, authenticated using (true);

drop policy if exists "Consulta pública de importações" on public.importacoes;
create policy "Consulta pública de importações"
  on public.importacoes for select to anon, authenticated using (true);

grant usage on schema public to anon, authenticated;
grant select on public.operacoes, public.importacoes to anon, authenticated;

